# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [434]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://github.com/guipsamora/pandas_exercises/blob/master/Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [54]:
data = pd.read_table('wind.data', sep='\s+', parse_dates=[[0, 1, 2]])
data.head(5)

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [55]:
import datetime
data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].apply(lambda x: datetime.date(x.year - 100, x.month, x.day))
data.head(5)

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [56]:
data['Yr_Mo_Dy'] = pd.to_datetime(data['Yr_Mo_Dy'])
data = data.set_index('Yr_Mo_Dy')

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [57]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [58]:
data.shape[1] - data.isnull().sum()

RPT     6
VAL     9
ROS    10
KIL     7
SHA    10
BIR    12
DUB     9
CLA    10
MUL     9
CLO    11
BEL    12
MAL     8
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [59]:
data.mean().mean()

10.227982360836924

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [60]:
loc_stats = data.describe()
loc_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
75%,15.920000,14.040000,14.670000,8.420000,13.540000,9.670000,12.960000,11.420000,11.190000,11.630000,16.880000,19.830000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [69]:
#day_stats = data.transpose().describe()
#day_stats.head(5)
data.transpose().describe()

Yr_Mo_Dy,1961-01-01 00:00:00,1961-01-02 00:00:00,1961-01-03 00:00:00,1961-01-04 00:00:00,1961-01-05 00:00:00,1961-01-06 00:00:00,1961-01-07 00:00:00,1961-01-08 00:00:00,1961-01-09 00:00:00,1961-01-10 00:00:00,...,1878-12-22 00:00:00,1878-12-23 00:00:00,1878-12-24 00:00:00,1878-12-25 00:00:00,1878-12-26 00:00:00,1878-12-27 00:00:00,1878-12-28 00:00:00,1878-12-29 00:00:00,1878-12-30 00:00:00,1878-12-31 00:00:00
count,11.000000,11.000000,11.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.00000,...,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,13.018182,11.336364,11.641818,6.619167,10.630000,8.240000,10.385000,10.487500,9.897500,10.47750,...,7.000833,15.613333,10.823333,5.729167,6.523333,16.708333,15.150000,14.890000,15.367500,15.402500
std,2.808875,3.188994,3.681912,3.198126,2.445356,2.998063,3.072114,3.547237,2.905954,3.44261,...,3.237337,3.850840,7.195039,3.583263,4.304510,7.868076,9.687857,5.756836,5.540437,5.702483
min,9.290000,6.500000,6.170000,1.790000,6.170000,4.420000,4.960000,5.910000,4.750000,6.54000,...,2.460000,9.500000,4.790000,0.750000,1.960000,8.080000,5.000000,8.710000,9.130000,9.590000
25%,10.540000,9.730000,9.315000,4.570000,9.807500,6.345000,8.237500,7.620000,7.977500,8.48750,...,5.077500,12.987500,5.840000,4.102500,3.070000,13.802500,9.095000,10.477500,12.375000,11.530000
50%,13.170000,10.830000,11.250000,5.855000,11.170000,7.810000,9.395000,9.685000,10.065000,9.35500,...,6.795000,15.395000,10.040000,5.230000,4.540000,15.025000,13.895000,14.210000,13.455000,12.080000
75%,15.000000,13.225000,12.730000,9.117500,12.170000,10.137500,13.572500,11.792500,11.267500,11.52250,...,8.765000,17.495000,11.970000,7.365000,10.722500,17.302500,16.700000,17.035000,18.185000,19.520000
max,18.500000,17.540000,18.500000,11.750000,13.330000,13.210000,14.290000,16.620000,15.370000,19.50000,...,13.080000,22.210000,31.710000,13.960000,13.830000,40.080000,41.460000,29.580000,28.790000,27.290000

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [77]:
data['month'] = data.index.month
data[data.month == 1].mean()

RPT      14.847325
VAL      12.914560
ROS      13.299624
KIL       7.199498
SHA      11.667734
BIR       8.054839
DUB      11.819355
CLA       9.512047
MUL       9.543208
CLO      10.053566
BEL      14.550520
MAL      18.028763
month     1.000000
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [83]:
data['year'] = data.index.year
data['day'] = data.index.day
data.query('month == 1 and day == 1')

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,month,year,day
Yr_Mo_Dy,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1,1961,1
1962-01-01,9.29,3.42,11.54,3.50,2.21,1.96,10.41,2.79,3.54,5.17,4.38,7.92,1,1962,1
1963-01-01,15.59,13.62,19.79,8.38,12.25,10.00,23.45,15.71,13.59,14.37,17.58,34.13,1,1963,1
1964-01-01,25.80,22.13,18.21,13.25,21.29,14.79,14.12,19.58,13.25,16.75,28.96,21.00,1,1964,1
1965-01-01,9.54,11.92,9.00,4.38,6.08,5.21,10.25,6.08,5.71,8.63,12.04,17.41,1,1965,1
1966-01-01,22.04,21.50,17.08,12.75,22.17,15.59,21.79,18.12,16.66,17.83,28.33,23.79,1,1966,1
1867-01-01,6.46,4.46,6.50,3.21,6.67,3.79,11.38,3.83,7.71,9.08,10.67,20.91,1,1867,1
1868-01-01,30.04,17.88,16.25,16.25,21.79,12.54,18.16,16.62,18.75,17.62,22.25,27.29,1,1868,1
1869-01-01,6.13,1.63,5.41,1.08,2.54,1.00,8.50,2.42,4.58,6.34,9.17,16.71,1,1869,1
1870-01-01,9.59,2.96,11.79,3.42,6.13,4.08,9.00,4.46,7.29,3.50,7.33,13.00,1,1870,1
1871-01-01,3.71,0.79,4.71,0.17,1.42,1.04,4.63,0.75,1.54,1.08,4.21,9.54,1,1871,1
1872-01-01,9.29,3.63,14.54,4.25,6.75,4.42,13.00,5.33,10.04,8.54,8.71,19.17,1,1872,1
1873-01-01,16.50,15.92,14.62,7.41,8.29,11.21,13.54,7.79,10.46,10.79,13.37,9.71,1,1873,1
1874-01-01,23.21,16.54,16.08,9.75,15.83,11.46,9.54,13.54,13.83,16.66,17.21,25.29,1,1874,1
1875-01-01,14.04,13.54,11.29,5.46,12.58,5.58,8.12,8.96,9.29,5.17,7.71,11.63,1,1875,1
1876-01-01,18.34,17.67,14.83,8.00,16.62,10.13,13.17,9.04,13.13,5.75,11.38,14.96,1,1876,1
1877-01-01,20.04,11.92,20.25,9.13,9.29,8.04,10.75,5.88,9.00,9.00,14.88,25.70,1,1877,1
1878-01-01,8.33,7.12,7.71,3.54,8.50,7.50,14.71,10.00,11.83,10.00,15.09,20.46,1,1878,1

### Step 13. Downsample the record to a monthly frequency for each location.

In [85]:
data.query("day == 1").head(5)

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,month,year,day
Yr_Mo_Dy,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1,1961,1
1961-02-01,14.25,15.12,9.04,5.88,12.08,7.17,10.17,3.63,6.50,5.50,9.17,8.00,2,1961,1
1961-03-01,12.67,13.13,11.79,6.42,9.79,8.54,10.25,13.29,NaN,12.21,20.62,NaN,3,1961,1
1961-04-01,8.38,6.34,8.33,6.75,9.33,9.54,11.67,8.21,11.21,6.46,11.96,7.17,4,1961,1
1961-05-01,15.87,13.88,15.37,9.79,13.46,10.17,9.96,14.04,9.75,9.92,18.63,11.12,5,1961,1

### Step 14. Downsample the record to a weekly frequency for each location.

In [87]:
data[::7].head(5)

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,month,year,day
Yr_Mo_Dy,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1,1961,1
1961-01-08,10.96,9.75,7.62,5.91,9.62,7.29,14.29,7.62,9.25,10.46,16.62,16.46,1,1961,8
1961-01-15,12.04,9.67,11.75,2.37,7.38,3.13,2.50,6.83,4.75,5.63,7.54,6.75,1,1961,15
1961-01-22,9.59,5.88,9.92,2.17,6.87,5.50,9.38,7.04,6.34,7.50,10.88,9.92,1,1961,22
1961-01-29,NaN,23.91,22.29,17.54,24.08,19.70,22.00,20.25,21.46,19.95,27.71,23.38,1,1961,29

### Step 15. Calculate the mean windspeed for each month in the dataset.  
#### Treat January 1961 and January 1962 as *different* months.
#### (hint: first find a  way to create an identifier unique for each month.)

In [88]:
data.groupby('month').mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,year,day
month,,,,,,,,,,,,,,
1,14.847325,12.914560,13.299624,7.199498,11.667734,8.054839,11.819355,9.512047,9.543208,10.053566,14.550520,18.028763,1902.833333,16.000000
2,13.710906,12.111122,12.879132,6.942411,11.551772,7.633858,11.206024,9.341437,9.313169,9.518051,13.728898,17.156142,1902.771654,14.614173
3,13.158687,11.505842,12.648118,7.265907,11.554516,7.959409,11.310179,9.635896,9.700324,10.096953,13.810609,16.909317,1902.833333,16.000000
4,12.555648,10.429759,12.204815,6.898037,10.677667,7.441389,10.221315,8.909056,8.930870,9.158019,12.664759,14.937611,1902.833333,15.500000
5,11.724032,10.145619,11.550394,6.307487,10.224301,6.942061,8.797738,8.452903,8.040806,8.524857,12.767258,13.736039,1902.833333,16.000000
6,10.451317,8.949704,10.361315,5.652278,9.529926,6.410093,8.009556,7.920796,7.639796,7.729185,12.246407,12.861818,1902.833333,15.500000
7,9.992007,8.357778,9.349642,5.416935,9.302634,5.972348,7.843501,7.262760,7.544480,7.321416,11.676505,12.800789,1902.833333,16.000000
8,10.213411,8.415143,9.993441,5.270681,8.901559,5.891057,7.772312,6.842025,7.240573,7.002783,11.110090,12.565943,1902.833333,16.000000
9,11.458519,9.981002,10.756883,5.615176,9.766315,6.566222,8.609722,7.745677,7.610556,7.689278,12.686389,14.761963,1902.833333,15.500000
10,12.660610,11.010681,11.453943,6.065215,10.550251,7.159910,9.387778,8.726308,8.347181,8.850376,14.155323,16.697151,1902.833333,16.000000
11,13.200722,11.639500,12.293407,6.247611,10.501130,7.134333,10.814861,8.427167,8.604000,8.943167,13.815741,18.114185,1902.833333,15.500000
12,14.446398,12.353602,13.212276,6.829910,11.301254,7.963710,11.849050,9.209355,9.447258,9.627670,14.259516,18.697599,1902.833333,16.000000

### Step 16. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [89]:
weekly = data.resample('W').agg(['min','max','mean','std'])

In [95]:
weekly.ix[:52, 'RPT':"MAL"]

              RPT                                VAL                    \
              min    max       mean       std    min    max       mean
Yr_Mo_Dy
1867-01-06   5.09  11.08   8.765000  2.568570   4.29  13.29   6.896667
1867-01-13   4.58  17.33  10.267143  3.965542   3.33  13.54   6.531429
1867-01-20  10.13  21.29  15.661429  4.190125   8.75  18.41  12.987143
1867-01-27   7.08  24.30  16.794286  5.924927  10.13  23.75  15.275714
1867-02-03  11.38  26.54  16.668571  5.259697  11.42  23.79  16.100000
1867-02-10   2.79   8.29   6.594286  1.943535   4.12  10.88   7.155714
1867-02-17   3.13  26.08  15.287143  7.156954   7.12  21.54  14.272857
1867-02-24  13.92  24.41  18.992857  3.872311  11.83  24.21  16.541429
1867-03-03  11.25  28.91  17.048571  5.935662  12.87  25.17  16.748571
1867-03-10   9.00  24.92  18.357143  4.903763   8.58  23.25  16.028571
1867-03-17   5.88  22.34  16.170000  5.873398   9.08  24.62  14.878571
1867-03-24   8.50  21.21  14.481429  4.668227   7.83  16.29   9.952857
1867-03-31   9.79  20.79  15.040000  3.751035   5.04  15.46  10.560000
1867-04-07  10.08  22.25  16.145714  4.722153   9.83  17.92  13.417143
1867-04-14   6.29  14.42  10.601429  3.546465   5.54  13.96  10.132857
1867-04-21   8.71  19.92  12.832857  4.427030   5.91  16.08   9.440000
1867-04-28   5.66  14.09   9.517143  2.682982   5.29  13.00   8.385714
1867-05-05   7.58  20.46  15.257143  4.318536   6.38  15.71  12.174286
1867-05-12   4.17  17.96  11.632857  5.328457   4.38  16.79  11.364286
1867-05-19   9.17  22.75  12.678571  4.529608  10.13  18.91  12.364286
1867-05-26   6.08  24.83  17.617143  6.882627   8.08  20.96  15.357143
1867-06-02   3.96  10.88   7.031429  2.567777   4.42   9.50   7.024286
1867-06-09   3.13  14.96   9.085714  4.160396   4.25  12.58   8.370000
1867-06-16   4.08   6.25   5.262857  0.935391   2.67   8.25   4.418571
1867-06-23   5.41  18.34  11.720000  3.883971   5.96  12.62   9.548571
1867-06-30   4.42  14.83  11.571429  3.830202   4.54  17.75   8.400000
1867-07-07   5.96  15.75  10.338571  3.434649   4.96  12.87   9.840000
1867-07-14   3.13  16.13   8.875714  4.705911   3.29  12.71   7.844286
1867-07-21   4.63  16.38   9.172857  4.031793   4.29  17.79   9.768571
1867-07-28   5.04  13.04   9.941429  3.229729   5.33  11.42   9.190000
1867-08-04   4.63  14.71  11.020000  3.857815   4.46  12.83   9.518571
1867-08-11   7.58  18.34  12.370000  4.205199   5.41  15.04   9.497143
1867-08-18   9.87  18.71  13.834286  2.921819   8.42  11.79  10.428571
1867-08-25   3.83  11.21   7.017143  2.827577   3.08  11.34   7.274286
1867-09-01   4.17  10.83   8.374286  2.515657   2.50   9.33   6.832857
1867-09-08   3.92  27.63  15.714286  9.123541   4.63  23.54  14.335714
1867-09-15   3.71  20.30   8.758571  6.477357   2.17  11.75   7.155714
1867-09-22   7.17  16.38  11.602857  3.806117   4.00  14.62   8.654286
1867-09-29  14.79  21.04  17.814286  1.976916  12.67  18.41  15.392857
1867-10-06   8.54  20.91  16.812857  4.231728  11.67  20.54  16.460000
1867-10-13   7.71  20.62  14.958571  4.562537   8.58  19.92  14.685714
1867-10-20  10.54  24.50  17.874286  4.807119  11.96  21.62  16.184286
1867-10-27   4.38  29.08  15.135714  8.186373   2.71  26.71  13.291429
1867-11-03   5.58  30.09  18.288571  7.754430   4.17  22.79  14.937143
1867-11-10   6.58  20.21  11.631429  4.496500   5.21  14.17   9.525714
1867-11-17   5.37  18.84  11.508571  4.489842   2.71  13.92   9.910000
1867-11-24   2.75  10.41   7.332857  3.152077   1.63  11.50   4.715714
1867-12-01   5.21  17.62  11.062857  3.838931   1.46  20.25  10.400000
1867-12-08   4.12  21.25  11.607143  6.356542   2.33  15.12   9.660000
1867-12-15   3.13  17.83   9.588571  5.356378   0.75  13.75   6.454286
1867-12-22   3.71  20.21  11.644286  6.427482   1.92  20.00  10.517143
1867-12-29   9.71  26.50  17.684286  5.352706   4.92  18.96  13.345714

                        ROS           ...           CLO              BEL  \
                 std    min    max    ...          mean       std    min
Yr_Mo_Dy                              ...
1867-01-06  3.567888   6.50  12.67    ...      6.098333  2.243323   2.54
1867-01-13  3.711816   5.17  12.87    ...      6.765714  3.086367   4.04
1867-01-20  3.437158   5.13  18.29    ...     11.215714  3.153405  10.37
1867-01-27  4.768095   8.00  19.38    ...     11.921429  3.782607   9.42
1867-02-03  4.466680  11.21  20.71    ...     16.737143  2.364957  17.50
1867-02-10  2.745298   4.21  16.71    ...      8.105714  1.799211   2.04
1867-02-17  4.664010   4.67  27.00    ...     11.935714  5.724738  10.71
1867-02-24  4.382143  13.00  20.96    ...     15.370000  2.702986   9.50
1867-03-03  5.135418   8.71  23.91    ...     16.757143  3.522327  14.71
1867-03-10  4.961406  11.12  21.87    ...     15.608571  4.620734   8.33
1867-03-17  5.738244   5.88  20.08    ...     15.665714  4.868524  16.33
1867-03-24  2.992728   8.17  16.46    ...     13.198571  1.730659  15.71
1867-03-31  4.815177   7.75  17.75    ...     11.037143  3.459628   5.83
1867-04-07  2.745073   7.87  25.54    ...     13.912857  2.905442  15.46
1867-04-14  3.765544  14.83  30.54    ...      8.490000  4.528223   4.88
1867-04-21  3.766201   4.71  14.29    ...     10.761429  3.545276   7.33
1867-04-28  3.027996   6.17  13.59    ...      7.590000  2.870883   5.04
1867-05-05  3.369213   9.25  19.00    ...     11.748571  3.582766   6.50
1867-05-12  4.976712   7.17  22.83    ...      6.170000  2.164640   6.38
1867-05-19  3.180246  10.63  23.25    ...      7.791429  1.973233  11.87
1867-05-26  4.621344   8.08  21.54    ...     12.870000  3.532478  10.08
1867-06-02  1.785458   4.08   8.92    ...      5.398571  1.955645   5.83
1867-06-09  3.139384   6.54  15.92    ...      9.157143  3.329007   6.96
1867-06-16  1.883440   2.37   9.29    ...      3.427143  1.288419   4.04
1867-06-23  2.404734   5.00  13.25    ...      7.594286  3.541868   6.00
1867-06-30  4.651555   5.25  16.13    ...      7.625714  3.721943   8.87
1867-07-07  2.678887   8.12  11.79    ...      8.415714  2.323983   9.13
1867-07-14  3.669400   3.96  11.87    ...      7.864286  3.524792   5.17
1867-07-21  5.233308   4.46  15.12    ...      9.417143  4.411099   4.08
1867-07-28  2.191377   5.66  15.04    ...      8.757143  3.381354   7.21
1867-08-04  2.986879   5.37  14.88    ...      9.118571  2.312786  12.50
1867-08-11  3.126919   7.71  12.96    ...      7.862857  2.990873   5.58
1867-08-18  1.156855   9.29  13.96    ...      8.911429  3.725844   7.54
1867-08-25  2.858641   4.25  13.62    ...      3.917143  2.635259   4.38
1867-09-01  2.214699   5.33   9.92    ...      6.262857  2.520811   4.54
1867-09-08  7.914503   4.54  20.04    ...     10.278571  6.022913   8.00
1867-09-15  3.860889   4.88  18.46    ...      4.840000  3.240926   2.54
1867-09-22  4.216554   6.25  13.46    ...      6.035714  2.723795   5.46
1867-09-29  1.882159  13.25  15.79    ...     10.661429  1.840312  13.29
1867-10-06  3.162299  10.37  18.63    ...     13.195714  2.469486  12.71
1867-10-13  3.989732   7.62  18.66    ...     11.351429  3.006263  14.00
1867-10-20  3.785802  10.13  22.42    ...     12.214286  4.588776   6.96
1867-10-27  8.033074   3.79  24.87    ...     11.625714  6.338057   8.87
1867-11-03  6.186272   5.75  19.67    ...     10.212857  4.374973   8.21
1867-11-10  3.091035   8.42  16.92    ...      6.400000  3.794702   9.50
1867-11-17  4.695764   8.46  15.71    ...     10.030000  4.284421   9.08
1867-11-24  3.468049   5.41  15.50    ...      3.945714  2.323323   3.75
1867-12-01  6.050306   6.29  13.70    ...      7.262857  3.066527   6.79
1867-12-08  4.561275   5.58  18.63    ...      8.195714  2.635279  12.54
1867-12-15  3.897614   2.83  19.04    ...      6.350000  2.885856   8.79
1867-12-22  6.877603   3.63  17.75    ...      6.905714  5.160100   5.50
1867-12-29  4.910770   8.54  18.96    ...     12.661429  3.422735   9.59

                                           MAL
              max       mean        std    min    max       mean       std
Yr_Mo_Dy
1867-01-06  10.67   5.631667   3.686296  11.67  20.91  15.140000  3.651997
1867-01-13  15.79  10.077143   3.573111   7.96  17.75  14.255714  3.277300
1867-01-20  22.63  14.778571   4.229592  11.75  20.88  17.671429  3.246626
1867-01-27  28.75  16.708571   6.058128  14.29  27.21  18.850000  4.796419
1867-02-03  25.92  22.165714   3.257411  16.54  26.79  21.635714  3.262938
1867-02-10  17.08  11.761429   5.208424  10.25  21.71  15.041429  3.720611
1867-02-17  23.75  15.635714   4.391457   8.08  34.62  17.957143  8.758717
1867-02-24  24.33  19.851429   5.499744  11.29  30.13  23.471429  6.317271
1867-03-03  31.13  22.417143   6.106518  16.54  31.66  25.772857  5.902140
1867-03-10  29.38  20.952857   9.022475  16.42  28.42  23.748571  4.922315
1867-03-17  30.75  23.125714   5.112823  17.00  37.59  26.888571  7.231714
1867-03-24  22.25  18.081429   2.300496  19.12  24.17  22.065714  1.794667
1867-03-31  24.17  15.892857   6.359918   9.29  27.84  20.898571  7.190801
1867-04-07  21.92  18.655714   2.622288  17.96  31.13  24.381429  4.820496
1867-04-14  18.00  11.144286   4.742573   6.08  16.29  12.275714  3.795097
1867-04-21  22.58  12.814286   6.237774  11.42  26.34  17.862857  5.476753
1867-04-28  17.04  11.392857   4.781087   7.83  16.42  12.314286  3.445571
1867-05-05  19.50  14.810000   4.879139  12.58  27.33  21.415714  5.945482
1867-05-12  16.38  10.345714   3.762605   4.79  16.79  11.385714  4.596364
1867-05-19  18.08  16.060000   2.142405  11.00  20.46  15.430000  3.390688
1867-05-26  21.75  16.168571   4.265401  10.79  25.25  16.248571  4.815819
1867-06-02  14.42   9.905714   3.200421   6.00  11.96   8.150000  2.536389
1867-06-09  18.63  13.321429   4.693387  10.71  22.67  15.892857  3.752185
1867-06-16   9.17   6.280000   1.734474   3.83  11.92   6.507143  2.641967
1867-06-23  18.46  11.882857   4.603375   5.54  23.87  13.627143  6.072168
1867-06-30  21.79  13.401429   4.287550   8.83  25.17  14.594286  6.872677
1867-07-07  18.63  15.068571   3.304852  10.79  22.25  15.755714  3.797630
1867-07-14  22.00  11.332857   6.723352   8.42  24.46  17.660000  6.254481
1867-07-21  20.75  12.742857   5.993560   7.00  18.38  13.625714  4.426217
1867-07-28  18.05  13.430000   3.470024   4.83  19.62  14.665714  5.086436
1867-08-04  18.96  16.444286   2.147688  13.54  22.50  16.618571  3.165093
1867-08-11  15.71  11.910000   3.238189   6.71  21.84  14.170000  5.128635
1867-08-18  15.00  11.858571   2.524707   7.21  24.96  13.471429  5.861130
1867-08-25  15.75   8.594286   3.818332   4.12  12.29   7.774286  2.508923
1867-09-01  16.92  10.994286   4.783443   9.04  22.04  13.934286  4.532195
1867-09-08  26.46  17.761429   6.591341   6.67  25.58  18.214286  7.797816
1867-09-15  16.13   9.858571   4.849266   3.54  18.41   9.455714  4.839294
1867-09-22  18.71  10.994286   5.119834   6.38  15.00  11.005714  3.074144
1867-09-29  21.59  18.101429   3.129709  14.09  19.55  16.811429  1.917737
1867-10-06  24.30  21.150000   4.256842  12.46  25.54  21.290000  4.353405
1867-10-13  24.83  18.912857   4.092370  11.54  23.38  18.564286  4.223762
1867-10-20  31.42  19.857143   8.252288  13.79  27.08  21.825714  5.578213
1867-10-27  38.96  19.987143  10.037348  13.88  34.54  21.048571  8.023267
1867-11-03  25.33  15.724286   5.004691  13.37  35.41  22.294286  6.933945
1867-11-10  20.91  15.261429   4.564670  12.62  25.50  18.312857  4.808880
1867-11-17  22.37  17.537143   5.353403  14.96  32.50  22.505714  7.090322
1867-11-24  15.34   7.767143   3.779434   5.58  18.29   9.374286  4.097259
1867-12-01  22.29  14.570000   4.775608   7.92  22.71  16.588571  4.433725
1867-12-08  21.75  17.838571   2.958082  16.00  27.12  22.720000  4.754826
1867-12-15  19.75  13.761429   4.226635  12.42  23.45  17.987143  4.088303
1867-12-22  25.37  13.410000   8.441177   9.67  22.75  16.058571  5.290975
1867-12-29  23.13  18.054286   4.775157  15.79  33.84  23.760000  7.271011

[52 rows x 48 columns]